server:
  port: 8081
spring:
  application:
    name: messaging
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: group-1
      auto-offset-reset: earliest
    producer:
      auto-offset-reset: earliest
